apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-config
data:
  application.yml: |
    spring:
      config:
        # import: optional:configserver:http://192.168.49.2:31270
        import: optional:configserver:http://10.105.96.116:8888
      application:
        name: discovery
