apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  application.yml: |
    server:
      port: 8040

    eureka:
      instance:
        host: 10.97.42.85
      client:
        service-url:
          defaultZone: http://10.97.42.85:8761/eureka

    spring:
      cloud:
        config:
          enabled: false
      data:
        mongodb:
          username: thuytien
          password: conghau
          host: 10.97.211.153
          port: 27017
          database: notification
          authentication-database: admin

      kafka:
        consumer:
          bootstrap-servers: kafka:9092
          group-id: test-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: '*'
            spring.json.type.mapping: fullSchoolResponse:com.example.notifications.FullSchoolResponse
