apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
      - name: gateway
        image: racingboy560/gateway
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: gateway-config
          mountPath: /app/application.yml
          subPath: application.yml
      volumes:
      - name: gateway-config
        configMap:
          name: gateway-config
