name: Build & Deploy Micro services on Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - discovery/**
      - gateway/**
      - notifications/**
      - school/**
      - student/**
      - 'docker-compose.yml'
      - .github/workflows/pipeline.yml
jobs:
  build-deploy:
    name: Build & Deploy Micro Services on Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose
      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d
          cd discovery && mvn clean package
          cd ../gateway && mvn clean package
          cd ../notifications && mvn clean package
          cd ../school && mvn clean package
          cd ../student && mvn clean package
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/discovery ./discovery
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/gateway ./gateway
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/notifications ./notifications
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/school ./school
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/student ./student
      - name: Login to Docket Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/discovery
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gateway
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/notifications
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/school
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student
          
          
